@CareBridgeApi_HostAddress = http://localhost:5246

GET {{CareBridgeApi_HostAddress}}/weatherforecast/
Accept: application/json

###



GET {{CareBridgeApi_HostAddress}}/api/patients
Accept: application/json

###

GET {{CareBridgeApi_HostAddress}}/api/patients/3
Accept: application/json

###
POST {{CareBridgeApi_HostAddress}}/api/patients
Content-Type: application/json

{
  "firstName": "Astarion",
  "lastName": "Ancunin",
  "dateOfBirth": "1913-04-16",
  "email": "astarion.ancunin@example.com",
  "phoneNumber": "555-013-7742"
}
###

PUT {{CareBridgeApi_HostAddress}}/api/patients/1
Content-Type: application/json

{
  "firstName": "Astarion",
  "lastName": "Ancunin",
  "dateOfBirth": "1913-04-16",
  "email": "astarion.ancunin@example.com",
  "phoneNumber": "555-013-7742"
}

### 

DELETE {{CareBridgeApi_HostAddress}}/api/patients/6

###
POST {{CareBridgeApi_HostAddress}}/api/providers
Content-Type: application/json

{
  "firstName": "Shadowheart",
  "lastName": "Hallowleaf",
  "specialty": "Internal Medicine",
  "email": "shadowheart.hallowleaf@example.com",
  "phoneNumber": "555-019-2486"
}

###

 POST {{CareBridgeApi_HostAddress}}/api/encounters
Content-Type: application/json

{
  "patientId": 1,
  "providerId": 1,
  "startDateTime": "2026-09-21T10:00:00Z",
  "encounterType": "Outpatient",
  "reasonForVisit": "Annual physical",
  "status": "Completed"
}